<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SecuriyConcept" nsURI="http://www.example.org/securityconcept"
    nsPrefix="SC">
  <eClassifiers xsi:type="ecore:EClass" name="SecurityGoal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityGoalClass" unique="false"
        eType="#//SecurityGoalClassType" defaultValueLiteral="Confidentiality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="damagePotential" eType="#//Damages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependsOnSecurityGoal"
        upperBound="-1" eType="#//SecurityGoal" eKeys="#//SecurityGoal/securityGoalID"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityGoalID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" lowerBound="1" eType="#//Asset"
        eOpposite="#//Asset/securitygoals"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threat" upperBound="-1"
        eType="#//Threat" eOpposite="#//Threat/securitygoal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Threat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threatID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attackPotential" eType="#//Damages"
        defaultValueLiteral="low"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securitygoal" lowerBound="1"
        upperBound="-1" eType="#//SecurityGoal" eOpposite="#//SecurityGoal/threat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependsOn" upperBound="-1"
        eType="#//SecurityGoal" eKeys="#//SecurityGoal/securityGoalID"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mitigates" lowerBound="1"
        upperBound="-1" eType="#//Threat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" upperBound="-1"
        eType="#//Connection" eOpposite="#//Connection/component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Data"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Subcomponents" upperBound="-1"
        eType="#//Component" eOpposite="#//Component/Ancestor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Ancestor" eType="#//Component"
        eOpposite="#//Component/Subcomponents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" eType="#//Asset"
        eOpposite="#//Asset/component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SecurityGoalClassType">
    <eLiterals name="Confidentiality"/>
    <eLiterals name="Integrity" value="1"/>
    <eLiterals name="Availability" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assetID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securitygoals" upperBound="-1"
        eType="#//SecurityGoal" eOpposite="#//SecurityGoal/asset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" eType="#//Component"
        eOpposite="#//Component/asset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Damages">
    <eLiterals name="low" literal="low"/>
    <eLiterals name="medium" value="1" literal="medium"/>
    <eLiterals name="high" value="2" literal="high"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityConcept">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityGoals" upperBound="-1"
        eType="#//SecurityGoal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threats" upperBound="-1"
        eType="#//Threat" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="#//Control" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assets" upperBound="-1"
        eType="#//Asset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="2"
        upperBound="2" eType="#//Component" eOpposite="#//Component/connection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" eType="#//Data"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" eType="#//Asset"
        eKeys="#//Asset/assetID"/>
  </eClassifiers>
</ecore:EPackage>
