/**
 *
 * $Id$
 */
package SecuriyConcept.validation;

import SecuriyConcept.Asset;
import SecuriyConcept.Component;
import SecuriyConcept.Connection;
import SecuriyConcept.Data;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SecuriyConcept.Component}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateIsAn(Asset value);
	boolean validateComponentID(int value);
	boolean validateConnection(EList<Connection> value);
	boolean validateData(EList<Data> value);
	boolean validateHasComponent(EList<Component> value);
	boolean validateHasAncestor(Component value);
}
