/**
 *
 * $Id$
 */
package SecuriyConcept.validation;

import SecuriyConcept.Component;
import SecuriyConcept.Data;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SecuriyConcept.Connection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnectionValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateConnectionID(int value);
	boolean validateComponent(EList<Component> value);
	boolean validateData(Data value);
}
