/**
 *
 * $Id$
 */
package SC.validation;

import SC.Asset;
import SC.Component;
import SC.Connection;
import SC.Data;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SC.Component}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateComponentID(int value);
	boolean validateSubcomponents(EList<Component> value);
	boolean validateAncestor(Component value);
	boolean validateAsset(Asset value);
	boolean validateData(EList<Data> value);

	boolean validateConnections(EList<Connection> value);

	boolean validateConnections(Connection value);

	boolean validateConnection(Connection value);
}
