/**
 *
 * $Id$
 */
package SC.validation;

import SC.Component;
import SC.Data;

/**
 * A sample validator interface for {@link SC.Connection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnectionValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateConnectionID(int value);
	boolean validateSource(Component value);
	boolean validateTarget(Component value);
	boolean validateData(Data value);
}
