/**
 *
 * $Id$
 */
package SC.validation;

import SC.Asset;
import SC.SecurityGoal;
import SC.Threat;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SC.Control}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ControlValidator {
	boolean validate();

	boolean validateControlID(int value);
	boolean validateName(String value);
	boolean validateDependsOn(EList<SecurityGoal> value);
	boolean validateAsset(EList<Asset> value);

	boolean validateThreats(EList<Threat> value);

	boolean validateMitigates(EList<Threat> value);
}
