/**
 *
 * $Id$
 */
package SC.validation;

import SC.Asset;
import SC.Damages;
import SC.SecurityGoal;

import SC.ThreatClass;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SC.Threat}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ThreatValidator {
	boolean validate();

	boolean validateThreatClass(ThreatClass value);

	boolean validateDescription(String value);
	boolean validateThreatID(int value);
	boolean validateAttackPotential(Damages value);
	boolean validateSecurityGoals(EList<SecurityGoal> value);

	boolean validateSecuritygoal(EList<SecurityGoal> value);

	boolean validateAsset(Asset value);
}
